// flow-typed signature: 2dc12df2eb46d329c22932c7ce7add7a
// flow-typed version: <<STUB>>/mobx-state-tree_v^3.14.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-state-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-state-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-state-tree/dist/mobx-state-tree' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.min' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.module' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.umd' {
  declare module.exports: any;
}

declare module 'mobx-state-tree/dist/mobx-state-tree.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-state-tree/dist/mobx-state-tree.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.min.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.min'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.module.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.module'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.umd.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.umd'>;
}
declare module 'mobx-state-tree/dist/mobx-state-tree.umd.min.js' {
  declare module.exports: $Exports<'mobx-state-tree/dist/mobx-state-tree.umd.min'>;
}
