export const mockedExchangeRatesResponse = {
    data: {
        timestamp: 1557054007,
        base: 'USD',
        rates:
            {
                AED: 3.673014,
                AFN: 77.499438,
                ALL: 110.45,
                AMD: 480.48986,
                ANG: 1.874844,
                AOA: 325.135,
                ARS: 44.446,
                AUD: 1.4243,
                AWG: 1.8,
                AZN: 1.7025,
                BAM: 1.753601,
                BBD: 2,
                BDT: 84.38,
                BGN: 1.74791,
                BHD: 0.377059,
                BIF: 1835,
                BMD: 1,
                BND: 1.350606,
                BOB: 6.90955,
                BRL: 3.9395,
                BSD: 1,
                BTC: 0.000172709073,
                BTN: 69.31288,
                BWP: 10.786129,
                BYN: 2.112959,
                BZD: 2.015591,
                CAD: 1.343703,
                CDF: 1636,
                CHF: 1.01685,
                CLF: 0.023958,
                CLP: 677.005,
                CNH: 6.734857,
                CNY: 6.734644,
                COP: 3240.42515,
                CRC: 595.205919,
                CUC: 1,
                CUP: 25.75,
                CVE: 98.9275,
                CZK: 22.9508,
                DJF: 178,
                DKK: 6.6662,
                DOP: 50.615,
                DZD: 119.659485,
                EGP: 17.1635,
                ERN: 14.99899,
                ETB: 29,
                EUR: 0.89194,
                FJD: 2.152842,
                FKP: 0.759129,
                GBP: 0.759129,
                GEL: 2.705,
                GGP: 0.759129,
                GHS: 5.18,
                GIP: 0.759129,
                GMD: 49.685,
                GNF: 9230,
                GTQ: 7.659456,
                GYD: 209.145546,
                HKD: 7.84515,
                HNL: 24.584925,
                HRK: 6.619037,
                HTG: 87.000153,
                HUF: 288.62,
                IDR: 14202.327728,
                ILS: 3.58308,
                IMP: 0.759129,
                INR: 69.178,
                IQD: 1190,
                IRR: 42105,
                ISK: 121.369769,
                JEP: 0.759129,
                JMD: 134.729243,
                JOD: 0.709004,
                JPY: 111.105,
                KES: 101.11,
                KGS: 68.708449,
                KHR: 4060,
                KMF: 440.374372,
                KPW: 900,
                KRW: 1164.33,
                KWD: 0.304181,
                KYD: 0.833274,
                KZT: 381.41,
                LAK: 8628.5,
                LBP: 1509.45,
                LKR: 176.907579,
                LRD: 173.37529,
                LSL: 14.36,
                LYD: 1.4,
                MAD: 9.66625,
                MDL: 17.830168,
                MGA: 3620,
                MKD: 55.0278,
                MMK: 1521.051433,
                MNT: 2453.75,
                MOP: 8.080494,
                MRO: 357,
                MRU: 36.77,
                MUR: 35.207,
                MVR: 15.400001,
                MWK: 734.536638,
                MXN: 18.918982,
                MYR: 4.142504,
                MZN: 64.050449,
                NAD: 14.4,
                NGN: 360,
                NIO: 33.07,
                NOK: 8.7006,
                NPR: 110.903644,
                NZD: 1.5049,
                OMR: 0.385011,
                PAB: 1,
                PEN: 3.314334,
                PGK: 3.36,
                PHP: 51.745104,
                PKR: 141.45,
                PLN: 3.8174,
                PYG: 6327.0557,
                QAR: 3.640999,
                RON: 4.239518,
                RSD: 105.350103,
                RUB: 65.0609,
                RWF: 905,
                SAR: 3.75041,
                SBD: 8.226062,
                SCR: 13.680528,
                SDG: 45.175,
                SEK: 9.538223,
                SGD: 1.3604,
                SHP: 0.759129,
                SLL: 8390,
                SOS: 584.5,
                SRD: 7.458,
                SSP: 130.2634,
                STD: 21050.59961,
                STN: 21.9,
                SVC: 8.749649,
                SYP: 515.093439,
                SZL: 14.465,
                THB: 31.879145,
                TJS: 9.429828,
                TMT: 3.499986,
                TND: 3.02541,
                TOP: 2.2829,
                TRY: 5.9644,
                TTD: 6.77275,
                TWD: 30.872,
                TZS: 2305.1,
                UAH: 26.608,
                UGX: 3769.749872,
                USD: 1,
                UYU: 35.100967,
                UZS: 8445,
                VEF: 248487.642241,
                VES: 5192.50683,
                VND: 23130.633181,
                VUV: 111.058203,
                WST: 2.626662,
                XAF: 585.074287,
                XAG: 0.066957,
                XAU: 0.00078191,
                XCD: 2.70255,
                XDR: 0.719582,
                XOF: 585.074287,
                XPD: 0.00072814,
                XPF: 106.436754,
                XPT: 0.00114746,
                YER: 250.350747,
                ZAR: 14.350975,
                ZMW: 12.924,
                ZWL: 322.355011
            }
    },
    status: 200,
    statusText: 'OK',
};
export const mockedGetCurrenciesResponse = {
    data: {
        AED: 'United Arab Emirates Dirham',
        AFN: 'Afghan Afghani',
        ALL: 'Albanian Lek',
        AMD: 'Armenian Dram',
        ANG: 'Netherlands Antillean Guilder',
        AOA: 'Angolan Kwanza',
        ARS: 'Argentine Peso',
        AUD: 'Australian Dollar',
        AWG: 'Aruban Florin',
        AZN: 'Azerbaijani Manat',
        BAM: 'Bosnia-Herzegovina Convertible Mark',
        BBD: 'Barbadian Dollar',
        BDT: 'Bangladeshi Taka',
        BGN: 'Bulgarian Lev',
        BHD: 'Bahraini Dinar',
        BIF: 'Burundian Franc',
        BMD: 'Bermudan Dollar',
        BND: 'Brunei Dollar',
        BOB: 'Bolivian Boliviano',
        BRL: 'Brazilian Real',
        BSD: 'Bahamian Dollar',
        BTC: 'Bitcoin',
        BTN: 'Bhutanese Ngultrum',
        BWP: 'Botswanan Pula',
        BYN: 'Belarusian Ruble',
        BZD: 'Belize Dollar',
        CAD: 'Canadian Dollar',
        CDF: 'Congolese Franc',
        CHF: 'Swiss Franc',
        CLF: 'Chilean Unit of Account (UF)',
        CLP: 'Chilean Peso',
        CNH: 'Chinese Yuan (Offshore)',
        CNY: 'Chinese Yuan',
        COP: 'Colombian Peso',
        CRC: 'Costa Rican Colón',
        CUC: 'Cuban Convertible Peso',
        CUP: 'Cuban Peso',
        CVE: 'Cape Verdean Escudo',
        CZK: 'Czech Republic Koruna',
        DJF: 'Djiboutian Franc',
        DKK: 'Danish Krone',
        DOP: 'Dominican Peso',
        DZD: 'Algerian Dinar',
        EGP: 'Egyptian Pound',
        ERN: 'Eritrean Nakfa',
        ETB: 'Ethiopian Birr',
        EUR: 'Euro',
        FJD: 'Fijian Dollar',
        FKP: 'Falkland Islands Pound',
        GBP: 'British Pound Sterling',
        GEL: 'Georgian Lari',
        GGP: 'Guernsey Pound',
        GHS: 'Ghanaian Cedi',
        GIP: 'Gibraltar Pound',
        GMD: 'Gambian Dalasi',
        GNF: 'Guinean Franc',
        GTQ: 'Guatemalan Quetzal',
        GYD: 'Guyanaese Dollar',
        HKD: 'Hong Kong Dollar',
        HNL: 'Honduran Lempira',
        HRK: 'Croatian Kuna',
        HTG: 'Haitian Gourde',
        HUF: 'Hungarian Forint',
        IDR: 'Indonesian Rupiah',
        ILS: 'Israeli New Sheqel',
        IMP: 'Manx pound',
        INR: 'Indian Rupee',
        IQD: 'Iraqi Dinar',
        IRR: 'Iranian Rial',
        ISK: 'Icelandic Króna',
        JEP: 'Jersey Pound',
        JMD: 'Jamaican Dollar',
        JOD: 'Jordanian Dinar',
        JPY: 'Japanese Yen',
        KES: 'Kenyan Shilling',
        KGS: 'Kyrgystani Som',
        KHR: 'Cambodian Riel',
        KMF: 'Comorian Franc',
        KPW: 'North Korean Won',
        KRW: 'South Korean Won',
        KWD: 'Kuwaiti Dinar',
        KYD: 'Cayman Islands Dollar',
        KZT: 'Kazakhstani Tenge',
        LAK: 'Laotian Kip',
        LBP: 'Lebanese Pound',
        LKR: 'Sri Lankan Rupee',
        LRD: 'Liberian Dollar',
        LSL: 'Lesotho Loti',
        LYD: 'Libyan Dinar',
        MAD: 'Moroccan Dirham',
        MDL: 'Moldovan Leu',
        MGA: 'Malagasy Ariary',
        MKD: 'Macedonian Denar',
        MMK: 'Myanma Kyat',
        MNT: 'Mongolian Tugrik',
        MOP: 'Macanese Pataca',
        MRO: 'Mauritanian Ouguiya (pre-2018)',
        MRU: 'Mauritanian Ouguiya',
        MUR: 'Mauritian Rupee',
        MVR: 'Maldivian Rufiyaa',
        MWK: 'Malawian Kwacha',
        MXN: 'Mexican Peso',
        MYR: 'Malaysian Ringgit',
        MZN: 'Mozambican Metical',
        NAD: 'Namibian Dollar',
        NGN: 'Nigerian Naira',
        NIO: 'Nicaraguan Córdoba',
        NOK: 'Norwegian Krone',
        NPR: 'Nepalese Rupee',
        NZD: 'New Zealand Dollar',
        OMR: 'Omani Rial',
        PAB: 'Panamanian Balboa',
        PEN: 'Peruvian Nuevo Sol',
        PGK: 'Papua New Guinean Kina',
        PHP: 'Philippine Peso',
        PKR: 'Pakistani Rupee',
        PLN: 'Polish Zloty',
        PYG: 'Paraguayan Guarani',
        QAR: 'Qatari Rial',
        RON: 'Romanian Leu',
        RSD: 'Serbian Dinar',
        RUB: 'Russian Ruble',
        RWF: 'Rwandan Franc',
        SAR: 'Saudi Riyal',
        SBD: 'Solomon Islands Dollar',
        SCR: 'Seychellois Rupee',
        SDG: 'Sudanese Pound',
        SEK: 'Swedish Krona',
        SGD: 'Singapore Dollar',
        SHP: 'Saint Helena Pound',
        SLL: 'Sierra Leonean Leone',
        SOS: 'Somali Shilling',
        SRD: 'Surinamese Dollar',
        SSP: 'South Sudanese Pound',
        STD: 'São Tomé and Príncipe Dobra (pre-2018)',
        STN: 'São Tomé and Príncipe Dobra',
        SVC: 'Salvadoran Colón',
        SYP: 'Syrian Pound',
        SZL: 'Swazi Lilangeni',
        THB: 'Thai Baht',
        TJS: 'Tajikistani Somoni',
        TMT: 'Turkmenistani Manat',
        TND: 'Tunisian Dinar',
        TOP: 'Tongan Pa\'anga',
        TRY: 'Turkish Lira',
        TTD: 'Trinidad and Tobago Dollar',
        TWD: 'New Taiwan Dollar',
        TZS: 'Tanzanian Shilling',
        UAH: 'Ukrainian Hryvnia',
        UGX: 'Ugandan Shilling',
        USD: 'United States Dollar',
        UYU: 'Uruguayan Peso',
        UZS: 'Uzbekistan Som',
        VEF: 'Venezuelan Bolívar Fuerte (Old)',
        VES: 'Venezuelan Bolívar Soberano',
        VND: 'Vietnamese Dong',
        VUV: 'Vanuatu Vatu',
        WST: 'Samoan Tala',
        XAF: 'CFA Franc BEAC',
        XAG: 'Silver Ounce',
        XAU: 'Gold Ounce',
        XCD: 'East Caribbean Dollar',
        XDR: 'Special Drawing Rights',
        XOF: 'CFA Franc BCEAO',
        XPD: 'Palladium Ounce',
        XPF: 'CFP Franc',
        XPT: 'Platinum Ounce',
        YER: 'Yemeni Rial',
        ZAR: 'South African Rand',
        ZMW: 'Zambian Kwacha',
        ZWL: 'Zimbabwean Dollar'
    },
    status: 200,
    statusText: 'OK',
};
export const mockedGetCurrentCurrencyResponse = {
    data: {
        currency: {code: 'RUB'}
    }
};
